### createAccount
POST http://localhost:8080/account
Content-Type: application/json

{
  "memberId": "hyeonju0121",
  "productionId": 1,
  "balance": 0
}

### createAccount
POST http://localhost:8080/account
Content-Type: application/json

{
  "memberId": "hyeonju0121",
  "productionId": 2,
  "balance": 12000
}

### createAccount
POST http://localhost:8080/account
Content-Type: application/json

{
  "memberId": "hyeonju0121",
  "productionId": 3,
  "balance": 8000
}

### deleteAccount
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "memberId": "hyeonju0121",
  "accountNumber": "981-1925-9394-59",
  "simplePassword": "123456",
  "transferAccountNumber": "989-5520-4912-11"
}